In [12]:
text="Amazing"
text=text.lower()
text_list=list(set(text))
text_list=sorted(text_list)
print(text_list)
index_key={}
char_key={}
for index, char in enumerate(text_list):
    index_key[index] = char
    char_key[char] = index

print(index_key)
print(char_key)
    


['a', 'g', 'i', 'm', 'n', 'z']
{0: 'a', 1: 'g', 2: 'i', 3: 'm', 4: 'n', 5: 'z'}
{'a': 0, 'g': 1, 'i': 2, 'm': 3, 'n': 4, 'z': 5}


In [13]:
word_index=[]
for i in text:
    word_index.append(char_key[i])

print(word_index)

[0, 3, 0, 5, 2, 4, 1]


In [19]:
sequence_length=4
features=[]
target=[]

for i in range(len(word_index) - sequence_length):
    features.append(word_index[i:i+sequence_length])
    target.append(word_index[i+sequence_length])

print(features)
print(target)

[[0, 3, 0, 5], [3, 0, 5, 2], [0, 5, 2, 4]]
[2, 4, 1]


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
model=Sequential(
    [
    SimpleRNN(128, input_shape=(sequence_length, len(text_list)), activation="relu"),
    Dense(len(text_list), activation="softmax")
    ]
)

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [28]:
import numpy as np
zeros_list=np.zeros([len(word_index)-sequence_length, sequence_length, len(text_list)])

for index, item in enumerate(features):
    for index2, item2 in enumerate(item):
        zeros_list[index, index2, item2] = 1

print(zeros_list)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
[[[1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]]]
