In [16]:
text="Looking forward"
text=text.lower()
text_list=list(set(text))
text_list=sorted(text_list)
print(text_list)
index_key={}
char_key={}
for index, char in enumerate(text_list):
    index_key[index] = char
    char_key[char] = index

print(index_key)
print(char_key)
    


[' ', 'a', 'd', 'f', 'g', 'i', 'k', 'l', 'n', 'o', 'r', 'w']
{0: ' ', 1: 'a', 2: 'd', 3: 'f', 4: 'g', 5: 'i', 6: 'k', 7: 'l', 8: 'n', 9: 'o', 10: 'r', 11: 'w'}
{' ': 0, 'a': 1, 'd': 2, 'f': 3, 'g': 4, 'i': 5, 'k': 6, 'l': 7, 'n': 8, 'o': 9, 'r': 10, 'w': 11}


In [17]:
word_index=[]
for i in text:
    word_index.append(char_key[i])

print(word_index)

[7, 9, 9, 6, 5, 8, 4, 0, 3, 9, 10, 11, 1, 10, 2]


In [18]:
sequence_length=4
features=[]
target=[]

for i in range(len(word_index) - sequence_length):
    features.append(word_index[i:i+sequence_length])
    target.append(word_index[i+sequence_length])

print(features)
print(target)

[[7, 9, 9, 6], [9, 9, 6, 5], [9, 6, 5, 8], [6, 5, 8, 4], [5, 8, 4, 0], [8, 4, 0, 3], [4, 0, 3, 9], [0, 3, 9, 10], [3, 9, 10, 11], [9, 10, 11, 1], [10, 11, 1, 10]]
[5, 8, 4, 0, 3, 9, 10, 11, 1, 10, 2]


In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
model=Sequential(
    [
    SimpleRNN(128, input_shape=(sequence_length, len(text_list)), activation="relu"),
    Dense(len(text_list), activation="softmax")
    ]
)

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])


In [20]:
import numpy as np
zeros_list=np.zeros([len(word_index)-sequence_length, sequence_length, len(text_list)])

for index, item in enumerate(features):
    for index2, item2 in enumerate(item):
        zeros_list[index, index2, item2] = 1

print(zeros_list)
target=np.expand_dims(target, axis=1)

[[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0

In [21]:
model.fit(zeros_list, target, epochs=50, batch_size=32)

Epoch 1/50


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 929ms/step - accuracy: 0.0000e+00 - loss: 2.5857
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.0000e+00 - loss: 2.5270
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.1818 - loss: 2.4728
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2727 - loss: 2.4204
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2727 - loss: 2.3691
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4545 - loss: 2.3190
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4545 - loss: 2.2695
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5455 - loss: 2.2193
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 2.1689
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7273 - loss: 2.1175
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7273 - loss: 2.0652
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8182 - loss: 2.0110
Epo

In [22]:
text="ooki".lower()
if len(text)<sequence_length:
    text=text.zfill(sequence_length)
if len(text)>sequence_length:
    text=text[0:sequence_length]

print(text)

text_num=[]
for i in text:
    text_num.append(char_key[i])

print(text_num)

ooki
[9, 9, 6, 5]


In [23]:
zeros_list=np.zeros([1, sequence_length, len(char_key)])

for index, item in enumerate(text_num):
    zeros_list[0, index, item] = 1
    print(index, item)

prediction=model.predict(zeros_list)
max_pred=np.argmax(prediction)
index_key[max_pred]

0 9
1 9
2 6
3 5


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


'n'

In [24]:
text="Looking forward to the sky above"
text=text.lower()
text_list_split = text.split()
text_list=sorted(text_list_split)
print(text_list)
index_key={}
char_key={}
for index, char in enumerate(text_list):
    index_key[index] = char
    char_key[char] = index

print(index_key)
print(char_key)
    


['above', 'forward', 'looking', 'sky', 'the', 'to']
{0: 'above', 1: 'forward', 2: 'looking', 3: 'sky', 4: 'the', 5: 'to'}
{'above': 0, 'forward': 1, 'looking': 2, 'sky': 3, 'the': 4, 'to': 5}


In [25]:
word_index=[]
for i in text_list_split:
    word_index.append(char_key[i])

print(word_index)

[2, 1, 5, 4, 3, 0]


In [26]:
sequence_length=1
features=[]
target=[]

for i in range(len(word_index) - sequence_length):
    features.append(word_index[i:i+sequence_length])
    target.append(word_index[i+sequence_length])

print(features)
print(target)

[[2], [1], [5], [4], [3]]
[1, 5, 4, 3, 0]


In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
model=Sequential(
    [
    SimpleRNN(128, input_shape=(sequence_length, len(text_list)), activation="relu"),
    Dense(len(text_list), activation="softmax")
    ]
)

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])


In [28]:
import numpy as np
zeros_list=np.zeros([len(word_index)-sequence_length, sequence_length, len(text_list)])

for index, item in enumerate(features):
    for index2, item2 in enumerate(item):
        zeros_list[index, index2, item2] = 1

print(zeros_list)
target=np.expand_dims(target, axis=1)

[[[0. 0. 1. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0.]]]


In [29]:
model.fit(zeros_list, target, epochs=50, batch_size=32)

Epoch 1/50


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 753ms/step - accuracy: 0.0000e+00 - loss: 1.9051
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.0000e+00 - loss: 1.8880
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0000e+00 - loss: 1.8710
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.8541
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.8374
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.8208
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.8043
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.7880
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.2000 - loss: 1.7717
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.7556
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.7395
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.7236

In [39]:
zeros_list=np.zeros([1, sequence_length, len(char_key)])
text="forward".lower()
text_num=[]
for i in text.split():
    text_num.append(char_key[i])

print(text_num)
for index, item in enumerate(text_num):
    zeros_list[0, index, item] = 1
    print(index, item)

prediction=model.predict(zeros_list)
max_pred=np.argmax(prediction)
index_key[max_pred]

[1]
0 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


'to'