In [64]:
text="Looking forward"
text=text.lower()
text_list=list(set(text))
text_list=sorted(text_list)
print(text_list)
index_key={}
char_key={}
for index, char in enumerate(text_list):
    index_key[index] = char
    char_key[char] = index

print(index_key)
print(char_key)
    


[' ', 'a', 'd', 'f', 'g', 'i', 'k', 'l', 'n', 'o', 'r', 'w']
{0: ' ', 1: 'a', 2: 'd', 3: 'f', 4: 'g', 5: 'i', 6: 'k', 7: 'l', 8: 'n', 9: 'o', 10: 'r', 11: 'w'}
{' ': 0, 'a': 1, 'd': 2, 'f': 3, 'g': 4, 'i': 5, 'k': 6, 'l': 7, 'n': 8, 'o': 9, 'r': 10, 'w': 11}


In [65]:
word_index=[]
for i in text:
    word_index.append(char_key[i])

print(word_index)

[7, 9, 9, 6, 5, 8, 4, 0, 3, 9, 10, 11, 1, 10, 2]


In [66]:
sequence_length=4
features=[]
target=[]

for i in range(len(word_index) - sequence_length):
    features.append(word_index[i:i+sequence_length])
    target.append(word_index[i+sequence_length])

print(features)
print(target)

[[7, 9, 9, 6], [9, 9, 6, 5], [9, 6, 5, 8], [6, 5, 8, 4], [5, 8, 4, 0], [8, 4, 0, 3], [4, 0, 3, 9], [0, 3, 9, 10], [3, 9, 10, 11], [9, 10, 11, 1], [10, 11, 1, 10]]
[5, 8, 4, 0, 3, 9, 10, 11, 1, 10, 2]


In [67]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
model=Sequential(
    [
    SimpleRNN(128, input_shape=(sequence_length, len(text_list)), activation="relu"),
    Dense(len(text_list), activation="softmax")
    ]
)

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])


In [68]:
import numpy as np
zeros_list=np.zeros([len(word_index)-sequence_length, sequence_length, len(text_list)])

for index, item in enumerate(features):
    for index2, item2 in enumerate(item):
        zeros_list[index, index2, item2] = 1

print(zeros_list)
target=np.expand_dims(target, axis=1)

[[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0

In [69]:
model.fit(zeros_list, target, epochs=50, batch_size=32)

Epoch 1/50


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 566ms/step - accuracy: 0.0000e+00 - loss: 2.5832
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0909 - loss: 2.5248
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.0909 - loss: 2.4688
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.0909 - loss: 2.4148
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0909 - loss: 2.3627
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4545 - loss: 2.3132
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8182 - loss: 2.2653
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9091 - loss: 2.2176
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 2.1705
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 2.1230
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 2.0752
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 2.0268
Epoch 1

In [70]:
text="ooki".lower()
if len(text)<sequence_length:
    text=text.zfill(sequence_length)
if len(text)>sequence_length:
    text=text[0:sequence_length]

print(text)

text_num=[]
for i in text:
    text_num.append(char_key[i])

print(text_num)

ooki
[9, 9, 6, 5]


In [71]:
zeros_list=np.zeros([1, sequence_length, len(char_key)])

for index, item in enumerate(text_num):
    zeros_list[0, index, item] = 1
    print(index, item)

prediction=model.predict(zeros_list)
max_pred=np.argmax(prediction)
index_key[max_pred]

0 9
1 9
2 6
3 5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


'n'